#!/bin/bash
# Quick cleanup commands for Licimar MVP
# Copy & paste any command below to cleanup your test data

echo "╔════════════════════════════════════════════════════════╗"
echo "║  LICIMAR MVP - Limpeza de Dados de Teste              ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""
echo "Copie e cole qualquer comando abaixo:"
echo ""
echo "1. Listar todos os pedidos:"
echo "   python clean_history.py listar-pedidos"
echo ""
echo "2. Deletar TODOS os pedidos:"
echo "   python clean_history.py limpar-pedidos"
echo ""
echo "3. Resetar TODAS as dívidas para 0:"
echo "   python clean_history.py limpar-dividas"
echo ""
echo "4. Limpar TUDO (pedidos + dívidas):"
echo "   python clean_history.py limpar-tudo"
echo ""
echo "5. Verificar dados de teste:"
echo "   cd backend/licimar_mvp_app && python check_test_data.py"
echo ""
echo "6. Fazer backup antes de deletar:"
echo "   cp backend/licimar_mvp_app/instance/licimar_dev.db backup_licimar_$(date +%Y%m%d_%H%M%S).db"
echo ""
echo "7. Resetar banco inteiro (CUIDADO!):"
echo "   python clean_history.py resetar-db"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Para mais informações, consulte: LIMPEZA_DADOS.md"
echo "═══════════════════════════════════════════════════════════"
echo ""
